title: <alexthetechguy.dev/>
subtitle: alexthetechguy.dev
email: itman91@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Alex's technical blog, simple, useful, educational, fun. Custom built from Jekyll site generation and minima theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alexthetechguy.dev"

theme: minima

show_excerpts: true

sass:
  quiet_deps: true
  silence_deprecations: [import]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
