title: <alexthetechguy.dev/>
subtitle: alexthetechguy.dev
email: itman91@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Alex's technical blog, simple, useful, educational, fun. Custom built from Jekyll site generation and minima theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alexthetechguy.dev"

theme: minima

show_excerpts: true

sass:
  quiet_deps: true
  silence_deprecations: [import]
